# Generated by Django 5.2.6 on 2025-09-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='social_network/images/', verbose_name='Изображение'),
        ),
    ]
